In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
X=np.array([1,2,4,3,5])
y=np.array([1,3,3,2,5])

In [15]:
def linear():
    y = B0 + B1 * x

In [16]:
X_mean=X-X.mean()
print(X_mean)
sqr_X_mean=X_mean*X_mean
y_mean=y-y.mean()
print(y_mean)
Sqr_X_mean_y_mean=X_mean*y_mean
print(Sqr_X_mean_y_mean)
Sum_Sqr_X_mean_y_mean=Sqr_X_mean_y_mean.sum()
print(Sum_Sqr_X_mean_y_mean)
B1= Sum_Sqr_X_mean_y_mean/sqr_X_mean.sum()
print(B1)

[-2. -1.  1.  0.  2.]
[-1.8  0.2  0.2 -0.8  2.2]
[ 3.6 -0.2  0.2 -0.   4.4]
8.0
0.8


In [17]:
def estimate():
    B1 = sum((Xi-mean(X)) * (yi-mean(y))) / sum((Xi- mean(X))^2)
    B0 = mean(y) - B1 * mean(X)

In [27]:
X_mean=X-X.mean()
print(X_mean)
sqr_X_mean=X_mean*X_mean


y_mean=y-y.mean()
print(y_mean)

Sqr_X_mean_y_mean=X_mean*y_mean
print(Sqr_X_mean_y_mean)
Sum_Sqr_X_mean_y_mean=Sqr_X_mean_y_mean.sum()
print(Sum_Sqr_X_mean_y_mean)


B1= Sum_Sqr_X_mean_y_mean/sqr_X_mean.sum()
print(B1)

[-2. -1.  1.  0.  2.]
[-1.8  0.2  0.2 -0.8  2.2]
[ 3.6 -0.2  0.2 -0.   4.4]
8.0
0.8


In [28]:
B0 = y.mean()-(B1*X.mean())
print(B0)
#Makin

0.39999999999999947


In [20]:
def predict():
    y_hat=B0+B1*X

In [29]:
y_hat=B0+B1*X
print(X,y,y_hat)

[1 2 4 3 5] [1 3 3 2 5] [1.2 2.  3.6 2.8 4.4]


In [23]:
def rmse():
    RMSE = sqrt( sum( ( y_hat_i - yi)^2 )/n )

In [25]:
n=np.size(X)
error=y_hat - y
print(error)
error_sqr=error*error
print(error)
RMSE = np.sqrt( error_sqr.sum()/n)
print(RMSE)

[ 0.2 -1.   0.6  0.8 -0.6]
[ 0.2 -1.   0.6  0.8 -0.6]
0.692820323027551
