In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('PUBG_Player_Statistics.csv')

In [4]:
df.head()

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
0      BreakNeck        4405                 3.14          17.65   
1      Blackwalk        8199                 4.41          18.18   
2  mercedes_benz        4454                 3.60           0.00   
3           DORA        7729                14.00          50.00   
4        n2tstar           0                10.50          33.33   

   solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
0           18469.14                 17          3                0.83   
1           33014.86                 33          6                0.36   
2            4330.44                  5          0                0.00   
3           13421.82                  8          4                0.67   
4            9841.04                  6          2                0.40   

   solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
0            4             23.5     ...               3751590.99   
1           11             33.3     ...               4295917.30   
2            1             20.0     ...               3935265.63   
3            6             75.0     ...               2738998.00   
4            5             83.3     ...               2347295.00   

   squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
0          5194786.58                2626.97                4372.64   
1          6051783.67                2422.48                6009.73   
2          5589608.74                1871.89                3011.87   
3          3796916.00                2154.62                5578.41   
4          3220260.00                2098.47                5642.54   

   squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
0             536.98         2186            234          1884   
1             734.85         2041            276          2340   
2             725.44         1766            210          2193   
3             587.28         1214            142          1252   
4             546.10         1245            120           923   

   squad_DamageDealt  squad_DBNOs  
0          242132.73         1448  
1          269795.75         1724  
2          292977.07         1897  
3          181106.90         1057  
4          160029.80         1077  

[5 rows x 152 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87898 entries, 0 to 87897
Columns: 152 entries, player_name to squad_DBNOs
dtypes: float64(83), int64(68), object(1)
memory usage: 101.9+ MB


In [6]:
df.columns.values

array(['player_name', 'tracker_id', 'solo_KillDeathRatio',
       'solo_WinRatio', 'solo_TimeSurvived', 'solo_RoundsPlayed',
       'solo_Wins', 'solo_WinTop10Ratio', 'solo_Top10s',
       'solo_Top10Ratio', 'solo_Losses', 'solo_Rating', 'solo_BestRating',
       'solo_DamagePg', 'solo_HeadshotKillsPg', 'solo_HealsPg',
       'solo_KillsPg', 'solo_MoveDistancePg', 'solo_RevivesPg',
       'solo_RoadKillsPg', 'solo_TeamKillsPg', 'solo_TimeSurvivedPg',
       'solo_Top10sPg', 'solo_Kills', 'solo_Assists', 'solo_Suicides',
       'solo_TeamKills', 'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideD

In [7]:
df[df['solo_WinRatio']>2].head()

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
0   BreakNeck        4405                 3.14          17.65   
1   Blackwalk        8199                 4.41          18.18   
3        DORA        7729                14.00          50.00   
4     n2tstar           0                10.50          33.33   
5  coldoxygen       33313                 5.73          31.25   

   solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
0           18469.14                 17          3                0.83   
1           33014.86                 33          6                0.36   
3           13421.82                  8          4                0.67   
4            9841.04                  6          2                0.40   
5           22003.22                 16          5                0.50   

   solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
0            4             23.5     ...               3751590.99   
1           11             33.3     ...               4295917.30   
3            6             75.0     ...               2738998.00   
4            5             83.3     ...               2347295.00   
5           10             62.5     ...               3218436.00   

   squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
0          5194786.58                2626.97                4372.64   
1          6051783.67                2422.48                6009.73   
3          3796916.00                2154.62                5578.41   
4          3220260.00                2098.47                5642.54   
5          4733977.00                2078.93                4414.86   

   squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
0             536.98         2186            234          1884   
1             734.85         2041            276          2340   
3             587.28         1214            142          1252   
4             546.10         1245            120           923   
5            1212.76         2023            195          2307   

   squad_DamageDealt  squad_DBNOs  
0          242132.73         1448  
1          269795.75         1724  
3          181106.90         1057  
4          160029.80         1077  
5          238640.00         1450  

[5 rows x 152 columns]

In [8]:
df['solo_WinRatio'].max()

100.0

In [9]:
df[df['solo_KillDeathRatio']>5].head()

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
3         DORA        7729                14.00          50.00   
4      n2tstar           0                10.50          33.33   
5   coldoxygen       33313                 5.73          31.25   
17    YoonRoot        4404                 5.06          18.46   
18      3N1GmA       19925                 6.60          37.50   

    solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
3            13421.82                  8          4                0.67   
4             9841.04                  6          2                0.40   
5            22003.22                 16          5                0.50   
17           87214.43                 65         12                0.49   
18           20927.23                 16          6                0.86   

    solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
3             6             75.0     ...               2738998.00   
4             5             83.3     ...               2347295.00   
5            10             62.5     ...               3218436.00   
17           29             44.6     ...               1170384.39   
18            7             43.8     ...               1429614.00   

    squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
3           3796916.00                2154.62                5578.41   
4           3220260.00                2098.47                5642.54   
5           4733977.00                2078.93                4414.86   
17          1711422.05                1843.02                3272.59   
18          2044366.00                2179.97                5069.55   

    squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
3              587.28         1214            142          1252   
4              546.10         1245            120           923   
5             1212.76         2023            195          2307   
17             610.58          566            120           650   
18             548.12          623            111           889   

    squad_DamageDealt  squad_DBNOs  
3           181106.90         1057  
4           160029.80         1077  
5           238640.00         1450  
17          103910.13          714  
18           80631.02          516  

[5 rows x 152 columns]

In [10]:
df['solo_KillDeathRatio'].max()

100.0

In [11]:
df[df['solo_KillDeathRatio']==100]

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
3739  ContinuousStrike      207460                100.0          85.71   

      solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
3739           12631.47                  7          6                0.92   

      solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
3739            7            100.0     ...                 94403.11   

      squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
3739           183782.18                2578.28                2368.43   

      squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
3739             404.38           75              4            88   

      squad_DamageDealt  squad_DBNOs  
3739           31836.55          227  

[1 rows x 152 columns]

In [12]:
df.shape

(87898, 152)

In [13]:
x = df.shape[0]
x

87898

In [14]:
r = range(1,x)
r

range(1, 87898)

In [15]:
df.iloc[1:3]

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
1      Blackwalk        8199                 4.41          18.18   
2  mercedes_benz        4454                 3.60           0.00   

   solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
1           33014.86                 33          6                0.36   
2            4330.44                  5          0                0.00   

   solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
1           11             33.3     ...               4295917.30   
2            1             20.0     ...               3935265.63   

   squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
1          6051783.67                2422.48                6009.73   
2          5589608.74                1871.89                3011.87   

   squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
1             734.85         2041            276          2340   
2             725.44         1766            210          2193   

   squad_DamageDealt  squad_DBNOs  
1          269795.75         1724  
2          292977.07         1897  

[2 rows x 152 columns]

In [16]:
df.iloc[1].isnull()

player_name                  False
tracker_id                   False
solo_KillDeathRatio          False
solo_WinRatio                False
solo_TimeSurvived            False
solo_RoundsPlayed            False
solo_Wins                    False
solo_WinTop10Ratio           False
solo_Top10s                  False
solo_Top10Ratio              False
solo_Losses                  False
solo_Rating                  False
solo_BestRating              False
solo_DamagePg                False
solo_HeadshotKillsPg         False
solo_HealsPg                 False
solo_KillsPg                 False
solo_MoveDistancePg          False
solo_RevivesPg               False
solo_RoadKillsPg             False
solo_TeamKillsPg             False
solo_TimeSurvivedPg          False
solo_Top10sPg                False
solo_Kills                   False
solo_Assists                 False
solo_Suicides                False
solo_TeamKills               False
solo_HeadshotKills           False
solo_HeadshotKillRat

In [17]:
df.iloc[2].isnull

<bound method Series.isnull of player_name                  mercedes_benz
tracker_id                            4454
solo_KillDeathRatio                    3.6
solo_WinRatio                            0
solo_TimeSurvived                  4330.44
solo_RoundsPlayed                        5
solo_Wins                                0
solo_WinTop10Ratio                       0
solo_Top10s                              1
solo_Top10Ratio                         20
solo_Losses                              5
solo_Rating                        1255.92
solo_BestRating                     1266.6
solo_DamagePg                       329.76
solo_HeadshotKillsPg                   0.6
solo_HealsPg                             1
solo_KillsPg                           3.6
solo_MoveDistancePg                 2804.8
solo_RevivesPg                           0
solo_RoadKillsPg                         0
solo_TeamKillsPg                         0
solo_TimeSurvivedPg                 866.09
solo_Top10sPg          

In [18]:
for i in r:
    if df.iloc[i].isnull==True:
        print('Empty')

In [19]:
df.head()

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
0      BreakNeck        4405                 3.14          17.65   
1      Blackwalk        8199                 4.41          18.18   
2  mercedes_benz        4454                 3.60           0.00   
3           DORA        7729                14.00          50.00   
4        n2tstar           0                10.50          33.33   

   solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
0           18469.14                 17          3                0.83   
1           33014.86                 33          6                0.36   
2            4330.44                  5          0                0.00   
3           13421.82                  8          4                0.67   
4            9841.04                  6          2                0.40   

   solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
0            4             23.5     ...               3751590.99   
1           11             33.3     ...               4295917.30   
2            1             20.0     ...               3935265.63   
3            6             75.0     ...               2738998.00   
4            5             83.3     ...               2347295.00   

   squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
0          5194786.58                2626.97                4372.64   
1          6051783.67                2422.48                6009.73   
2          5589608.74                1871.89                3011.87   
3          3796916.00                2154.62                5578.41   
4          3220260.00                2098.47                5642.54   

   squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
0             536.98         2186            234          1884   
1             734.85         2041            276          2340   
2             725.44         1766            210          2193   
3             587.28         1214            142          1252   
4             546.10         1245            120           923   

   squad_DamageDealt  squad_DBNOs  
0          242132.73         1448  
1          269795.75         1724  
2          292977.07         1897  
3          181106.90         1057  
4          160029.80         1077  

[5 rows x 152 columns]

In [20]:
df.as_matrix()

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


array([['BreakNeck', 4405, 3.14, ..., 1884, 242132.73, 1448],
       ['Blackwalk', 8199, 4.41, ..., 2340, 269795.75, 1724],
       ['mercedes_benz', 4454, 3.6, ..., 2193, 292977.07, 1897],
       ...,
       ['Dertydann', 178547, 1.0, ..., 95, 15939.11, 92],
       ['Neferhor', 126589, 5.1, ..., 317, 56870.07, 350],
       ['pepperedangus', 66362, 0.83, ..., 150, 19769.59, 140]],
      dtype=object)

In [21]:
pd.DataFrame(df.as_matrix()).head()

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


0     1     2      3        4   5   6     7   8     9    ...   \
0      BreakNeck  4405  3.14  17.65  18469.1  17   3  0.83   4  23.5  ...    
1      Blackwalk  8199  4.41  18.18  33014.9  33   6  0.36  11  33.3  ...    
2  mercedes_benz  4454   3.6      0  4330.44   5   0     0   1    20  ...    
3           DORA  7729    14     50  13421.8   8   4  0.67   6    75  ...    
4        n2tstar     0  10.5  33.33  9841.04   6   2   0.4   5  83.3  ...    

           142          143      144      145     146   147  148   149  \
0  3.75159e+06  5.19479e+06  2626.97  4372.64  536.98  2186  234  1884   
1  4.29592e+06  6.05178e+06  2422.48  6009.73  734.85  2041  276  2340   
2  3.93527e+06  5.58961e+06  1871.89  3011.87  725.44  1766  210  2193   
3    2.739e+06  3.79692e+06  2154.62  5578.41  587.28  1214  142  1252   
4   2.3473e+06  3.22026e+06  2098.47  5642.54   546.1  1245  120   923   

      150   151  
0  242133  1448  
1  269796  1724  
2  292977  1897  
3  181107  1057  
4  160030  1077  

[5 rows x 152 columns]

In [22]:
df[df.isin(['NaN'])].head()

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
0         NaN         NaN                  NaN            NaN   
1         NaN         NaN                  NaN            NaN   
2         NaN         NaN                  NaN            NaN   
3         NaN         NaN                  NaN            NaN   
4         NaN         NaN                  NaN            NaN   

   solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
0                NaN                NaN        NaN                 NaN   
1                NaN                NaN        NaN                 NaN   
2                NaN                NaN        NaN                 NaN   
3                NaN                NaN        NaN                 NaN   
4                NaN                NaN        NaN                 NaN   

   solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
0          NaN              NaN     ...                      NaN   
1          NaN              NaN     ...                      NaN   
2          NaN              NaN     ...                      NaN   
3          NaN              NaN     ...                      NaN   
4          NaN              NaN     ...                      NaN   

   squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
0                 NaN                    NaN                    NaN   
1                 NaN                    NaN                    NaN   
2                 NaN                    NaN                    NaN   
3                 NaN                    NaN                    NaN   
4                 NaN                    NaN                    NaN   

   squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
0                NaN          NaN            NaN           NaN   
1                NaN          NaN            NaN           NaN   
2                NaN          NaN            NaN           NaN   
3                NaN          NaN            NaN           NaN   
4                NaN          NaN            NaN           NaN   

   squad_DamageDealt  squad_DBNOs  
0                NaN          NaN  
1                NaN          NaN  
2                NaN          NaN  
3                NaN          NaN  
4                NaN          NaN  

[5 rows x 152 columns]

In [23]:
df[df['player_name'].isin(['Black','White', 'Crystal','BreakNeck'])].head(3)

player_name  tracker_id  solo_KillDeathRatio  solo_WinRatio  \
0       BreakNeck        4405                 3.14          17.65   
39143       Black       11636                 2.75           9.09   

       solo_TimeSurvived  solo_RoundsPlayed  solo_Wins  solo_WinTop10Ratio  \
0               18469.14                 17          3                0.83   
39143           25873.83                 22          2                0.29   

       solo_Top10s  solo_Top10Ratio     ...       squad_RideDistance  \
0                4             23.5     ...               3751590.99   
39143            7             31.8     ...                208150.10   

       squad_MoveDistance  squad_AvgWalkDistance  squad_AvgRideDistance  \
0              5194786.58                2626.97                4372.64   
39143           354942.60                1790.15                2538.42   

       squad_LongestKill  squad_Heals  squad_Revives  squad_Boosts  \
0                 536.98         2186            234          1884   
39143             199.82          146             16           146   

       squad_DamageDealt  squad_DBNOs  
0              242132.73         1448  
39143           19903.67          121  

[2 rows x 152 columns]

In [24]:
print('this many columns:%d ' % len(df.columns))
df.columns

this many columns:152 


Index(['player_name', 'tracker_id', 'solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       ...
       'squad_RideDistance', 'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt', 'squad_DBNOs'],
      dtype='object', length=152)

In [25]:
df[df['solo_WinRatio'].isnull()].head(10)

Empty DataFrame
Columns: [player_name, tracker_id, solo_KillDeathRatio, solo_WinRatio, solo_TimeSurvived, solo_RoundsPlayed, solo_Wins, solo_WinTop10Ratio, solo_Top10s, solo_Top10Ratio, solo_Losses, solo_Rating, solo_BestRating, solo_DamagePg, solo_HeadshotKillsPg, solo_HealsPg, solo_KillsPg, solo_MoveDistancePg, solo_RevivesPg, solo_RoadKillsPg, solo_TeamKillsPg, solo_TimeSurvivedPg, solo_Top10sPg, solo_Kills, solo_Assists, solo_Suicides, solo_TeamKills, solo_HeadshotKills, solo_HeadshotKillRatio, solo_VehicleDestroys, solo_RoadKills, solo_DailyKills, solo_WeeklyKills, solo_RoundMostKills, solo_MaxKillStreaks, solo_WeaponAcquired, solo_Days, solo_LongestTimeSurvived, solo_MostSurvivalTime, solo_AvgSurvivalTime, solo_WinPoints, solo_WalkDistance, solo_RideDistance, solo_MoveDistance, solo_AvgWalkDistance, solo_AvgRideDistance, solo_LongestKill, solo_Heals, solo_Revives, solo_Boosts, solo_DamageDealt, solo_DBNOs, duo_KillDeathRatio, duo_WinRatio, duo_TimeSurvived, duo_RoundsPlayed, duo_Wins, duo_WinTop10Ratio, duo_Top10s, duo_Top10Ratio, duo_Losses, duo_Rating, duo_BestRating, duo_DamagePg, duo_HeadshotKillsPg, duo_HealsPg, duo_KillsPg, duo_MoveDistancePg, duo_RevivesPg, duo_RoadKillsPg, duo_TeamKillsPg, duo_TimeSurvivedPg, duo_Top10sPg, duo_Kills, duo_Assists, duo_Suicides, duo_TeamKills, duo_HeadshotKills, duo_HeadshotKillRatio, duo_VehicleDestroys, duo_RoadKills, duo_DailyKills, duo_WeeklyKills, duo_RoundMostKills, duo_MaxKillStreaks, duo_WeaponAcquired, duo_Days, duo_LongestTimeSurvived, duo_MostSurvivalTime, duo_AvgSurvivalTime, duo_WinPoints, duo_WalkDistance, duo_RideDistance, duo_MoveDistance, duo_AvgWalkDistance, duo_AvgRideDistance, duo_LongestKill, duo_Heals, duo_Revives, duo_Boosts, ...]
Index: []

[0 rows x 152 columns]

In [26]:
df.isnull().sum().sort_values(ascending=True)

player_name                0
duo_Heals                  0
duo_Revives                0
duo_Boosts                 0
duo_DamageDealt            0
duo_DBNOs                  0
squad_KillDeathRatio       0
squad_WinRatio             0
squad_TimeSurvived         0
squad_RoundsPlayed         0
squad_Wins                 0
squad_WinTop10Ratio        0
squad_Top10s               0
squad_Top10Ratio           0
squad_Losses               0
squad_Rating               0
duo_LongestKill            0
squad_BestRating           0
duo_AvgRideDistance        0
duo_MoveDistance           0
duo_HeadshotKillRatio      0
duo_VehicleDestroys        0
duo_RoadKills              0
duo_DailyKills             0
duo_WeeklyKills            0
duo_RoundMostKills         0
duo_MaxKillStreaks         0
duo_WeaponAcquired         0
duo_Days                   0
duo_LongestTimeSurvived    0
                          ..
duo_KillsPg                0
duo_MoveDistancePg         0
duo_RevivesPg              0
duo_RoadKillsP

In [27]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [28]:
c.shape

(3, 3)

In [29]:
print(c)

[[-6.00369845e-01 -5.47144406e-01  4.15121644e-01]
 [ 1.04729379e-02  1.23784212e-03 -1.85303587e-02]
 [ 4.24918717e-01  1.32881589e+00 -1.52794955e+00]]


In [30]:
a

array([[-1.09927772, -1.00182189,  0.7600881 ],
       [ 1.09853382,  0.12984049, -1.94369772],
       [ 0.32193853,  1.00677381, -1.1576469 ]])

In [31]:
b

array([[0.54614938],
       [0.00953356],
       [1.3198753 ]])

In [35]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [41]:
a= np.random.randn(3,4)
b= np.random.randn(4,1)

print (a,'\n')
print (b)

[[ 1.84762284  0.5562969  -0.39652323  0.52944586]
 [ 1.5961696  -0.81842467  1.00933165 -0.33707545]
 [ 0.10734078 -0.5986554   0.18796363  0.80023951]] 

[[-0.1439611 ]
 [-1.42908344]
 [ 0.10628701]
 [ 0.37281053]]


In [42]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [44]:
c = a + b.T
print(c)

[[ 1.70366175 -0.87278654 -0.29023621  0.90225638]
 [ 1.45220851 -2.24750811  1.11561866  0.03573507]
 [-0.03662032 -2.02773885  0.29425064  1.17305004]]


In [46]:
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [47]:
c = a.T + b
print(c)

[[ 1.70366175  1.45220851 -0.03662032]
 [-0.87278654 -2.24750811 -2.02773885]
 [-0.29023621  1.11561866  0.29425064]
 [ 0.90225638  0.03573507  1.17305004]]


In [48]:
c = a.T + b.T
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [49]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.73850728 -0.2993357  -0.44652071]
 [ 0.45648248 -0.3339925   0.3425478 ]
 [-0.62343264  0.18986003 -0.36125833]]


In [50]:
import numpy as np
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [52]:
import Python_DHT

ModuleNotFoundError: No module named 'Python_DHT'