# Indexin in 2D array

In [4]:
import numpy as np

In [11]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [12]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[0]

array([ 5, 10, 15])

In [14]:
arr_2d[0][1]

10

In [15]:
arr_2d[0,1]

10

In [16]:
arr_2d(0,1)

TypeError: 'numpy.ndarray' object is not callable

In [17]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [18]:
my_arr = np.arange(50).reshape(5,10)

In [19]:
my_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
my_arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d * arr_2d

array([[  25,  100,  225],
       [ 400,  625,  900],
       [1225, 1600, 2025]])

In [24]:
arr_2d / arr_2d

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
my_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr

NameError: name 'arr' is not defined

In [27]:
arr = np.arange(10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])