In [2]:
x = "My name is Ramesh Pradhan"

In [3]:
x[3:7]

'name'

In [4]:
my_list = ['a', 'b', 'c']

In [7]:
my_list.append('d')

In [8]:
print(my_list)

['a', 'b', 'c', 'd']


In [9]:
t=(1,2,3)

In [10]:
t

(1, 2, 3)

In [11]:
t[0]

1

In [12]:
t[0:]

(1, 2, 3)

In [13]:
t[:3]

(1, 2, 3)

In [14]:
t[:2]

(1, 2)

In [15]:
{1,2,3}

{1, 2, 3}

In [16]:
{111,333}

{111, 333}

In [17]:
s

NameError: name 's' is not defined

In [18]:
{1,1,2,2,3,3}

{1, 2, 3}

In [19]:
s={1,2,3}

In [20]:
s

{1, 2, 3}

In [21]:
s.add(111)

In [22]:
s

{1, 2, 3, 111}

In [23]:
s.add(1,2,1,3,4)

TypeError: add() takes exactly one argument (5 given)

In [24]:
s.add(3)

In [25]:
s

{1, 2, 3, 111}

In [26]:
s.add(55)

In [27]:
s

{1, 2, 3, 55, 111}

In [28]:
if 3<5:
    print('Hello you are right')

Hello you are right


In [33]:
if 1==2:
    print('You are wrong')
else:
        print('You are right')

You are right


In [35]:
if 1==2:
    print('First')
elif 1==1:
    print('Middle')


Middle


In [36]:
x=[1,3,2,6,5]

In [39]:
for temp in x:
    print('hello')

hello
hello
hello
hello
hello


In [40]:
for temp in x:
    print(temp)

1
3
2
6
5


In [5]:
i = 1
while i<7:
    print('i is : {num}'.format(num=i))
    i=i+1

i is : 1
i is : 2
i is : 3
i is : 4
i is : 5
i is : 6


In [12]:
for temp in range(0,5):
    print(temp)

0
1
2
3
4


In [9]:
x = range(3,5)

In [10]:
x

range(3, 5)

In [11]:
for temp in x:
    print(temp)

3
4


In [21]:
x = [1, 2, 3, 4, 5]
out = []
for temp in x:
    out.append(temp**2)
print(out)

[1, 4, 9, 16, 25]


In [20]:
print(out)

[1, 4, 9, 16, 25]


In [23]:
def square(num):
    """
    This is the documentation string
    It is used to find the square of any digit
    """
    return num**2

In [24]:
square(2)

4

In [45]:
def times2(num):
    return num*2

In [26]:
seq = [1,2,3,4,5]

In [27]:
map(times2, seq)

In [47]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [46]:
times2(3)

6

##lamba

In [50]:
t = lambda var:var*2

In [51]:
list(map(lambda num:num*2, seq))

[2, 4, 6, 8, 10]

In [55]:
list(filter(lambda x:x%2==0, seq))

[2, 4]

In [56]:
tweet = "Hello there! My name is #Ramesh Pradhan"

In [57]:
tweet.split('#')

['Hello there! My name is ', 'Ramesh Pradhan']

In [58]:
tweet.split('#')[1]

'Ramesh Pradhan'

In [59]:
tweet.split('#')[0]

'Hello there! My name is '

In [60]:
tweet.split('#')[2]

IndexError: list index out of range

In [61]:
def cube(num):
    return num**3

In [62]:
my_seq=[1,2,3,4,5,6]

In [63]:
list(map(cube, my_seq))

[1, 8, 27, 64, 125, 216]

In [66]:
lb = lambda z : z **3

In [67]:
list(filter(lb%2==0, my_seq))

TypeError: unsupported operand type(s) for %: 'function' and 'int'

In [76]:
list(map(lambda x:x%2, my_seq))

[1, 0, 1, 0, 1, 0]

In [78]:
tweet.split('#')[0]

'Hello there! My name is '

In [79]:
unpack = [(1,2),(3,4),(5,6)]

In [80]:
unpack

[(1, 2), (3, 4), (5, 6)]

In [81]:
unpack[0]

(1, 2)

In [82]:
unpack[0][0]

1

In [83]:
for x in unpack:
    print (x)

(1, 2)
(3, 4)
(5, 6)


In [85]:
for a,b in unpack:
    print (a)

1
3
5


In [1]:
x = [1,2,3,4]

In [3]:
[num ** 2 for num in x]

[1, 4, 9, 16]

In [4]:
seq = [1,2,3,4]

In [5]:
def square(num):
    return num **2

In [12]:
for x in seq :
    y = square(x)
    print ([y])

[1]
[4]
[9]
[16]


In [13]:
list(map(square, seq))

[1, 4, 9, 16]

In [21]:
list(map(lambda x : x%2, seq))

[1, 0, 1, 0]

In [22]:
x

4

In [23]:
lst

NameError: name 'lst' is not defined

In [24]:
lst = [1,2,3,4]

In [25]:
1 in lst

True

In [26]:
lst.index(1)

0

In [27]:
lst.shape()

AttributeError: 'list' object has no attribute 'shape'

In [28]:
import numpy as np

In [31]:
lst = np.random.randint(0,50,10)

In [32]:
lst

array([ 7, 11, 16,  5, 20,  1, 22,  1,  4,  9])

In [33]:
lst.argmax()

6

In [34]:
lst.shape

(10,)

In [35]:
lst

array([ 7, 11, 16,  5, 20,  1, 22,  1,  4,  9])

In [36]:
lst[0:3]=1

In [37]:
lst

array([ 1,  1,  1,  5, 20,  1, 22,  1,  4,  9])

In [38]:
lst[:]

array([ 1,  1,  1,  5, 20,  1, 22,  1,  4,  9])

In [39]:
lst = np.random.randint(0,50,15)

In [40]:
lst

array([18, 39, 22, 34,  3, 40,  2,  0, 19,  5, 12, 13,  9, 44, 34])

In [41]:
lst.argmax()

13

In [42]:
myslice = lst[0:6]

In [43]:
myslice

array([18, 39, 22, 34,  3, 40])

In [44]:
myslicewhole = lst[:]

In [45]:
myslicewhole

array([18, 39, 22, 34,  3, 40,  2,  0, 19,  5, 12, 13,  9, 44, 34])

In [46]:
myslice[0:5]=3

In [47]:
lst

array([ 3,  3,  3,  3,  3, 40,  2,  0, 19,  5, 12, 13,  9, 44, 34])

In [64]:
myslice[0:5]=np.random.randint(0,100,5)

In [65]:
lst

array([16, 51, 65, 43, 68, 40,  2,  0, 19,  5, 12, 13,  9, 44, 34])

myslice

In [66]:
myslice

array([16, 51, 65, 43, 68, 40])

In [67]:
myslice[:]

array([16, 51, 65, 43, 68, 40])

In [68]:
my_copy = myslice.copy()

In [69]:
my_copy

array([16, 51, 65, 43, 68, 40])

In [72]:
my_copy[:]=np.random.randint(0,100,6)

In [73]:
my_copy

array([10, 18, 67, 21, 86, 55])

In [74]:
myslice

array([16, 51, 65, 43, 68, 40])

In [75]:
lst>5

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True], dtype=bool)

In [76]:
lst

array([16, 51, 65, 43, 68, 40,  2,  0, 19,  5, 12, 13,  9, 44, 34])

In [77]:
lst[lst>5]

array([16, 51, 65, 43, 68, 40, 19, 12, 13,  9, 44, 34])